services:
  db:
    image: mysql:lts
    env_file:
      - ./docker/mysql/.${APP_ENV}.env
    volumes:
      - db_data_dev:/var/lib/mysql
      - ./sql/import.sql:/docker-entrypoint-initdb.d/import.sql
    restart: always
    ports:
      - "${DB_PORT}:${DB_PORT}"

    container_name: videgrenier-db-${APP_ENV}


  website:
    image: ghcr.io/doubleriichi/videgrenier-app:${APP_ENV}-latest
    # env_file:
    #   - .env
      
    # build:
    #   context: .
    #   dockerfile: dockerfile
    #   args:
    #     APACHE_VHOST: ${APP_ENV}
    #     PORT: ${APACHE_PORT}

    depends_on:
      - db
    ports:
      - "${APACHE_PORT}:${APACHE_PORT}"
    restart: always
    container_name: videgrenier-web-${APP_ENV}


volumes:
  db_data_dev:
 