services:
  db:
    image: mysql:lts
    env_file:
      - ./docker/mysql/.${APP_ENV}.env
    volumes:
      - db_data_${APP_ENV}:/var/lib/mysql
      - ./sql/import.sql:/docker-entrypoint-initdb.d/import.sql
    restart: always
    ports:
      - "${DB_PORT}:3306" 

    container_name: videgrenier-db-${APP_ENV}

  website:
    image: ghcr.io/doubleriichi/videgrenier-app:${APP_ENV}-latest

    depends_on:
      - db
    ports:
      - "${APACHE_PORT}:${APACHE_PORT}"
    restart: always
    container_name: videgrenier-web-${APP_ENV}

volumes:
  db_data_dev:
  db_data_prod: