name: Build Image docker en environment de Dev

on:
  push:
    branches:
      - master
      - main

jobs:
  build-and-push:
    name: Build & Push Docker image to GHCR
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
    
    env:
      APACHE_VHOST: prod
      APACHE_PORT: 8081
      DB_PORT: 3308
      APP_ENV: prod

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Log in to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - name: Generate .env file from secrets
        run: |
          echo "DB_HOST=${{ secrets.DB_HOST }}" >> .env
          echo "DB_USER=${{ secrets.DB_USER }}" >> .env
          echo "DB_NAME=${{ secrets.DB_NAME }}" >> .env
          echo "DB_PASSWORD=${{ secrets.DB_PASSWORD }}" >> .env
          echo $DB_PORT >> .env

      - name: Build and push Docker image to GHCR
        run: |
          IMAGE_ID=ghcr.io/doubleriichi/videgrenier-app
          docker build \
            --build-arg APACHE_VHOST=$APACHE_VHOST \
            --build-arg PORT=$APACHE_PORT \
            -t $IMAGE_ID:$APP_ENV-latest \
            -f dockerfile .
          
          docker push $IMAGE_ID:$APP_ENV-latest
